apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: default
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
        version: 1.0.0
    spec:
      containers:
      - name: product
        image: rahadiangg/demo-istio:product-svc-1.0.0
        resources:
          limits:
            memory: "20Mi"
            cpu: "20m"
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: default
spec:
  selector:
    app: product
  ports:
  - port: 8000
    targetPort: 8000
    name: http

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-virtualservice
  namespace: default
spec:
  hosts:
  - product.default.svc.cluster.local
  http:
  - name: "route full"
    route:
    - destination:
        host: product.default.svc.cluster.local # disarankan menggunakan format DNS full (FQDN)
      weight: 100