---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - grafana-srikandi-app.rahadian.dev
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: grafana-cert-rahadian-dev
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-gateway-vs
  namespace: istio-system
spec:
  gateways:
    - grafana-gateway
  hosts:
    - grafana-srikandi-app.rahadian.dev
  http:
    - route:
        - destination:
            host: prom-stack-grafana.observability.svc.cluster.local
            port:
              number: 80
          weight: 100
