---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: srikandi-app
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - srikandi-app.rahadian.dev
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: srikandi-cert-rahadian-dev
    
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: srikandi-app-vs
  namespace: istio-system
spec:
  gateways:
    - srikandi-app
  hosts:
    - srikandi-app.rahadian.dev
  http:
    - route:
        - destination:
            host: sifood-srikandi-dashboard.default.svc.cluster.local
            port:
              number: 3000
          weight: 100